controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    sword = sprites.createProjectileFromSprite(img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .............ccc........
        ............cddc........
        ...........cddc.........
        .........ccddc..........
        .........cddc...........
        .......ddccc............
        .......dd...............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, DOOD_KILLER_PERSON, 200, 0)
})
info.onLifeZero(function () {
    DOOD_KILLER_PERSON.destroy()
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    DOOD_DEAD_GHOST.destroy(effects.fire, 500)
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    DOOD_DEAD_GHOST.destroy(effects.fire, 500)
    info.changeLifeBy(-1)
})
let DOOD_DEAD_GHOST: Sprite = null
let sword: Sprite = null
let DOOD_KILLER_PERSON: Sprite = null
scene.setBackgroundColor(7)
info.setLife(3)
DOOD_KILLER_PERSON = sprites.create(img`
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff......ccc.
    .ffefbf44fbfeff....cddc.
    .ffefbf44fbfeff...cddc..
    .fee4dddddd4eef.ccddc...
    fdfeeddddd4eeffecddc....
    fbffee4444ee4fddccc.....
    fbf4f222222f1edde.......
    fcf.f222222f44ee........
    .ff.f445544f............
    ....ffffffff............
    .....ff..ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
DOOD_KILLER_PERSON.setFlag(SpriteFlag.StayInScreen, true)
controller.moveSprite(DOOD_KILLER_PERSON)
game.onUpdateInterval(2000, function () {
    DOOD_DEAD_GHOST = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    DOOD_DEAD_GHOST.setVelocity(-100, 0)
    DOOD_DEAD_GHOST.follow(DOOD_KILLER_PERSON, 50)
    DOOD_DEAD_GHOST.left = scene.screenWidth()
    DOOD_DEAD_GHOST.setFlag(SpriteFlag.AutoDestroy, true)
})
