scene.onOverlapTile(SpriteKind.Player, sprites.builtin.coral3, function (sprite, location) {
    statusbar.value += -50
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    sword = sprites.createProjectileFromSprite(img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .............ccc........
        ............cddc........
        ...........cddc.........
        .........ccddc..........
        .........cddc...........
        .......ddccc............
        .......dd...............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, DOOD_KILLER_PERSON, 200, 0)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (DOOD_KILLER_PERSON.vy == 0) {
        DOOD_KILLER_PERSON.vy = -150
    }
})
statusbars.onZero(StatusBarKind.Health, function (status) {
    game.over(false, effects.dissolve)
})
scene.onOverlapTile(SpriteKind.Player, sprites.builtin.forestTiles8, function (sprite, location) {
    game.over(true, effects.confetti)
})
let sword: Sprite = null
let DOOD_KILLER_PERSON: Sprite = null
let statusbar: StatusBarSprite = null
scene.setBackgroundColor(9)
tiles.setTilemap(tilemap`level1`)
statusbar = statusbars.create(20, 4, StatusBarKind.Health)
statusbar.setLabel("Health")
statusbar.attachToSprite(DOOD_KILLER_PERSON)
statusbar.setOffsetPadding(0, 10)
statusbar.value = 100
DOOD_KILLER_PERSON = sprites.create(img`
    . . . . 2 2 2 2 2 e . . . . . . 
    . . . 2 2 2 2 d 2 2 e . . . . . 
    . . e 2 2 2 2 2 2 2 e . . . . . 
    . . e 2 2 2 2 2 2 2 e . . . . . 
    . . e 2 2 2 2 2 e f f c c . . . 
    . . e e 2 2 e f f f f b c . . . 
    . e e e f e 2 b f f f d c . . . 
    e e 2 2 d f 2 1 1 1 1 b c . . . 
    e e 2 2 d f e e c c c . . . . . 
    b 1 1 d e 2 2 e e c . . . . . . 
    . f f e 2 2 2 2 e . . . . . . . 
    . . f f d d 2 2 f f d d . . . . 
    . . f f d d e e f f d d . . . . 
    . . . f f f f . . . . . . . . . 
    . . e e e f f f . . . . . . . . 
    . . e e e e f f f . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(DOOD_KILLER_PERSON, 100, 0)
DOOD_KILLER_PERSON.ay = 350
scene.cameraFollowSprite(DOOD_KILLER_PERSON)
