controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    sword = sprites.createProjectileFromSprite(img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .............ccc........
        ............cddc........
        ...........cddc.........
        .........ccddc..........
        .........cddc...........
        .......ddccc............
        .......dd...............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, DOOD_KILLER_PERSON, 200, 0)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    DOOD_KILLER_PERSON.vy = -150
})
info.onLifeZero(function () {
    DOOD_KILLER_PERSON.destroy()
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
	
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
	
})
let sword: Sprite = null
let DOOD_KILLER_PERSON: Sprite = null
tiles.setTilemap(tilemap`level1`)
info.setLife(3)
DOOD_KILLER_PERSON = sprites.create(img`
    . . . . 2 2 2 2 2 e . . . . . . 
    . . . 2 2 2 2 d 2 2 e . . . . . 
    . . e 2 2 2 2 2 2 2 e . . . . . 
    . . e 2 2 2 2 2 2 2 e . . . . . 
    . . e 2 2 2 2 2 e f f c c . . . 
    . . e e 2 2 e f f f f b c . . . 
    . e e e f e 2 b f f f d c . . . 
    e e 2 2 d f 2 1 1 1 1 b c . . . 
    e e 2 2 d f e e c c c . . . . . 
    b 1 1 d e 2 2 e e c . . . . . . 
    . f f e 2 2 2 2 e . . . . . . . 
    . . f f d d 2 2 f f d d . . . . 
    . . f f d d e e f f d d . . . . 
    . . . f f f f . . . . . . . . . 
    . . e e e f f f . . . . . . . . 
    . . e e e e f f f . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(DOOD_KILLER_PERSON, 100, 0)
DOOD_KILLER_PERSON.ay = 350
scene.cameraFollowSprite(DOOD_KILLER_PERSON)
game.onUpdateInterval(2000, function () {
	
})
